version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      time: "11:00"
      timezone: Asia/Kolkata
    open-pull-requests-limit: 25

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "11:00"
      timezone: Asia/Kolkata
    open-pull-requests-limit: 25
