[tool.poetry]
name        = "decrypto-api"
version     = "0.1.0"
description = "Decrypto API"
authors     = [ "Your Name <you@example.com>" ]

[tool.poetry.dependencies]
python            = "^3.9"
alembic           = "^1.6.5"
colorama          = "^0.4.4"
emails            = "^0.6"
fastapi           = "^0.68.0"
gunicorn          = "^20.1.0"
Jinja2            = "^3.0.1"
passlib           = { extras = [ "argon2" ], version = "^1.7.4" }
psycopg2          = "^2.9.1"
pydantic          = { extras = [ "dotenv", "email" ], version = "^1.8.2" }
python-jose       = { extras = [ "cryptography" ], version = "^3.3.0" }
python-multipart  = "^0.0.5"
SQLAlchemy        = "^1.4.22"
starlette-context = "^0.3.3"
structlog         = "^21.1.0"
tenacity          = "^8.0.1"
uvicorn           = { extras = [ "standard" ], version = "^0.15.0" }

[tool.poetry.dev-dependencies]
black             = { version = "^21.6b0", allow-prereleases = true }
docformatter      = { version = "^1.4", allow-prereleases = true }
isort             = { version = "^5.9.2", allow-prereleases = true }
mypy              = { version = "^0.910", allow-prereleases = true }
pylint            = { version = "^2.10.2", allow-prereleases = true }
pytest            = { version = "^6.2.4", allow-prereleases = true }
pytest-cov        = { version = "^2.12.1", allow-prereleases = true }
sqlalchemy2-stubs = { version = "^0.0.2a10", allow-prereleases = true }

[build-system]
requires      = [ "poetry-core>=1.0.0" ]
build-backend = "poetry.core.masonry.api"

# Configuration for other tools

[tool.coverage.run]
omit = [
    "app/db/init_db.py",
    "app/initial_data.py",
    "app/pre_start.py",
    "app/tests_pre_start.py",
    "app/tests/*",
]

[tool.isort]
profile           = "black"
known_first_party = [ "app" ]

[tool.mypy]
disallow_untyped_defs = true
plugins               = [ "sqlalchemy.ext.mypy.plugin" ]

[tool.pylint.master]
extension-pkg-whitelist = "pydantic"

[tool.pylint.messages_control]
disable = []

[tool.pylint.reports]
output-format = "colorized"
