[tool.poetry]
name        = "decrypto-api"
version     = "0.1.0"
description = "Decrypto API"
authors     = [ "Your Name <you@example.com>" ]

[tool.poetry.dependencies]
python           = "^3.9"
alembic          = "^1.6.5"
emails           = "^0.6"
fastapi          = "^0.66.0"
Jinja2           = "^3.0.1"
passlib          = "^1.7.4"
psycopg2         = "^2.9.1"
pydantic         = { extras = [ "dotenv", "email" ], version = "^1.8.2" }
python-jose      = { extras = [ "cryptography" ], version = "^3.3.0" }
python-multipart = "^0.0.5"
SQLAlchemy       = "^1.4.22"
tenacity         = "^8.0.1"
uvicorn          = { extras = [ "standard" ], version = "^0.14.0" }
coloredlogs      = "^15.0.1"

[tool.poetry.dev-dependencies]
black             = { version = "^21.6b0", allow-prereleases = true }
docformatter      = { version = "^1.4", allow-prereleases = true }
isort             = { version = "^5.9.2", allow-prereleases = true }
mypy              = { version = "^0.910", allow-prereleases = true }
pylint            = { version = "^2.9.3", allow-prereleases = true }
pytest            = { version = "^6.2.4", allow-prereleases = true }
pytest-cov        = { version = "^2.12.1", allow-prereleases = true }
sqlalchemy2-stubs = { version = "^0.0.2-alpha.4", allow-prereleases = true }

[build-system]
requires      = [ "poetry-core>=1.0.0" ]
build-backend = "poetry.core.masonry.api"

# Configuration for other tools

[tool.isort]
profile           = "black"
known_first_party = [ "app" ]

[tool.mypy]
disallow_untyped_defs = true
plugins               = [ "sqlalchemy.ext.mypy.plugin" ]

[tool.pylint.master]
extension-pkg-whitelist = "pydantic"

[tool.pylint.messages_control]
disable = []

[tool.pylint.reports]
output-format = "colorized"
