"""Create questionorderitem table

Revision ID: 134a669901ab
Revises: d6d0cc1fa62c
Create Date: 2021-07-25 17:59:09.879723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '134a669901ab'
down_revision = 'd6d0cc1fa62c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decrypto_questionorderitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['decrypto_question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decrypto_questionorderitem_id'), 'decrypto_questionorderitem', ['id'], unique=False)
    op.create_index(op.f('ix_decrypto_questionorderitem_question_id'), 'decrypto_questionorderitem', ['question_id'], unique=True)
    op.create_index(op.f('ix_decrypto_questionorderitem_question_number'), 'decrypto_questionorderitem', ['question_number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decrypto_questionorderitem_question_number'), table_name='decrypto_questionorderitem')
    op.drop_index(op.f('ix_decrypto_questionorderitem_question_id'), table_name='decrypto_questionorderitem')
    op.drop_index(op.f('ix_decrypto_questionorderitem_id'), table_name='decrypto_questionorderitem')
    op.drop_table('decrypto_questionorderitem')
    # ### end Alembic commands ###
