"""Create initial tables

Revision ID: b2d68b32e08a
Revises: 
Create Date: 2021-07-17 16:46:10.200524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2d68b32e08a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decrypto_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decrypto_user_email'), 'decrypto_user', ['email'], unique=True)
    op.create_index(op.f('ix_decrypto_user_full_name'), 'decrypto_user', ['full_name'], unique=False)
    op.create_index(op.f('ix_decrypto_user_id'), 'decrypto_user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decrypto_user_id'), table_name='decrypto_user')
    op.drop_index(op.f('ix_decrypto_user_full_name'), table_name='decrypto_user')
    op.drop_index(op.f('ix_decrypto_user_email'), table_name='decrypto_user')
    op.drop_table('decrypto_user')
    # ### end Alembic commands ###
