"""
Create initial tables.

Revision ID: b7911b838101
Revises:
Create Date: 2021-12-21 17:46:47.461596
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b7911b838101"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "decrypto_question",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("answer", sa.String(), nullable=False),
        sa.Column("content", sa.LargeBinary(), nullable=False),
        sa.Column("content_type", sa.String(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_decrypto_question_answer"),
        "decrypto_question",
        ["answer"],
        unique=True,
    )
    op.create_index(
        op.f("ix_decrypto_question_id"), "decrypto_question", ["id"], unique=False
    )
    op.create_table(
        "decrypto_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=True),
        sa.Column("question_number", sa.Integer(), nullable=False),
        sa.Column(
            "question_number_updated_at", sa.DateTime(timezone=True), nullable=False
        ),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_decrypto_user_email"), "decrypto_user", ["email"], unique=True
    )
    op.create_index(
        op.f("ix_decrypto_user_full_name"), "decrypto_user", ["full_name"], unique=False
    )
    op.create_index(op.f("ix_decrypto_user_id"), "decrypto_user", ["id"], unique=False)
    op.create_index(
        op.f("ix_decrypto_user_username"), "decrypto_user", ["username"], unique=True
    )
    op.create_table(
        "decrypto_questionorderitem",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question_number", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"], ["decrypto_question.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_decrypto_questionorderitem_id"),
        "decrypto_questionorderitem",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_decrypto_questionorderitem_question_id"),
        "decrypto_questionorderitem",
        ["question_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_decrypto_questionorderitem_question_number"),
        "decrypto_questionorderitem",
        ["question_number"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_decrypto_questionorderitem_question_number"),
        table_name="decrypto_questionorderitem",
    )
    op.drop_index(
        op.f("ix_decrypto_questionorderitem_question_id"),
        table_name="decrypto_questionorderitem",
    )
    op.drop_index(
        op.f("ix_decrypto_questionorderitem_id"),
        table_name="decrypto_questionorderitem",
    )
    op.drop_table("decrypto_questionorderitem")
    op.drop_index(op.f("ix_decrypto_user_username"), table_name="decrypto_user")
    op.drop_index(op.f("ix_decrypto_user_id"), table_name="decrypto_user")
    op.drop_index(op.f("ix_decrypto_user_full_name"), table_name="decrypto_user")
    op.drop_index(op.f("ix_decrypto_user_email"), table_name="decrypto_user")
    op.drop_table("decrypto_user")
    op.drop_index(op.f("ix_decrypto_question_id"), table_name="decrypto_question")
    op.drop_index(op.f("ix_decrypto_question_answer"), table_name="decrypto_question")
    op.drop_table("decrypto_question")
    # ### end Alembic commands ###
