"""Create question table

Revision ID: d6d0cc1fa62c
Revises: b2d68b32e08a
Create Date: 2021-07-18 16:14:10.266576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6d0cc1fa62c'
down_revision = 'b2d68b32e08a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decrypto_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decrypto_question_answer'), 'decrypto_question', ['answer'], unique=True)
    op.create_index(op.f('ix_decrypto_question_id'), 'decrypto_question', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decrypto_question_id'), table_name='decrypto_question')
    op.drop_index(op.f('ix_decrypto_question_answer'), table_name='decrypto_question')
    op.drop_table('decrypto_question')
    # ### end Alembic commands ###
